server:
  undertow:
    direct-buffers: true
    io-threads: 8
    worker-threads: 64 # io-threads * 8
    buffer-size: 1024
    accesslog:
      enabled: true

spring:
  task:
    execution:
      thread-name-prefix: snowman-task-
      pool:
        core-size: 10
        max-size: 20

logging:
  name: snowman
  config: classpath:logback-spring.xml
  file:
    path: logs
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    cc.kevinlu.snow.server.data.mapper: DEBUG
